matrix:
    include:
        - os: linux
          dist: trusty
          sudo: true
          script:
            - sudo ./bupc-install.sh
        - os: osx
          osx_image: xcode8.2
          script:
            - ./bupc-install.sh
language: generic
