language: c
matrix:
    include:
        - os: linux
          dist: trusty
          sudo: true
          env: BUILD=http
        - os: linux
          dist: trusty
          sudo: true
          env: BUILD=local
        - os: osx
          osx_image: xcode8.2
          env: BUILD=http
        - os: osx
          osx_image: xcode8.2
          install: brew install homebrew/dupes/make
          env: BUILD=local
    allow_failures:
    - env: BUILD=local
    fast_finish: true
cache:
    directories:
    - ~/.upcc/temp
script:
- |
  case "$BUILD" in
    http)
      sudo DEBUG=true ./bupc-install.sh
      ;;
    local)
      sudo DEBUG=true ./bupc-install.sh -l
      ;;
  esac
