matrix:
    include:
        - os: linux
          dist: trusty
          sudo: true
        - os: osx
          osx_image: xcode8.2
          install: brew install homebrew/dupes/make
language: c
script:
  - ./bupc-install.sh -l
